server:
  port: 8080
postgres:
  dsn: postgres://postgres:postgres@172.17.16.110:5432/postgres
  min: 3
  max: 10
watch_path: /Users/Abel/Downloads
white_list:
  /login:
    - POST
  /activate: [ GET ]
