server:
  port: 8080
postgres:
  dsn: postgres://postgres:postgres@172.17.16.109:5432/postgres
  min: 3
  max: 10
watch_path: /Users/Abel/Downloads
jwt:
  key: 0xa06f853898a9dd4f32441a56879c52878f96c42730ed31c50e00
white_list:
  /login:
    - POST
  /show/*: [ GET ]
  /visit/*: [ GET ]
  /download/*: [ GET ]
  /: [ GET ]
  /assets/*: [ GET ]
  /favicon.ico: [ GET ]
