server:
  port: 8080
postgres:
  dsn: postgres://seafile_rw:agYx0DzkYsRASuQT@postgresql:5432/seafile
  min: 3
  max: 10
watch_path: /home
jwt:
  key: 0xa06f853898a9dd4f32441a56879c52878f96c42730ed31c50e00
white_list:
  /login:
    - POST
  /show/*: [ GET ]
  /visit/*: [ GET ]
  /download/*: [ GET ]
  /: [ GET ]
  /assets/*: [ GET ]
  /favicon.ico: [ GET ]
