// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/AppProvider.vue')['default']
    Button: typeof import('./src/components/button.vue')['default']
    DialogContent: typeof import('./src/components/DialogContent.vue')['default']
    Input: typeof import('./src/components/input.vue')['default']
    MessageContent: typeof import('./src/components/MessageContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
