name: Rust

on:
  push:
    branches: [ "build-action" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 编译前端
      run: cd webapp && yarn install && yarn build
    - name: 编译后端
      run: cargo build --release --verbose
#    - name: Run tests
#      run: cargo test --verbose
