name: SeaFile CI/CD

on:
  push:
    branches: [ "build-action" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-vue:
    name: 编译前端
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Node_Modules
        uses: actions/cache@v3
        with:
          path: ./webapp/node_modules
          key: node_modules-${{ github.ref_name }}
          restore-keys: SeaFile-Cache
      - name: Build Vue
        run: |
          cd webapp && yarn install && yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist
  build-rust:
    name: 编译后端
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Target
        uses: actions/cache@v3
        with:
          path: ./target
          key: target-${{ github.ref_name }}
          restore-keys: SeaFile-Cache
      - name: Build Rust
        run: |
          cargo build --release --verbose
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: seafile
          path: ./target/release/seafile
  build-image:
    name: 构建镜像
    runs-on: ubuntu-latest
    needs:
      - build-vue
      - build-rust
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./
        run: ls ./
      - uses: actions/download-artifact@v2
        with:
          name: seafile
          path: ./
        run: ls ./
      - name: Docker Build
        run: |
          ls ./
