name: Rust

on:
  push:
    branches: [ "build-action" ]
  pull_request:
    branches: [ "dev01" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: auraco/rust:alpine
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
#    - name: Run tests
#      run: cargo test --verbose
